### ISSUE TITLE
mkbundle fails with `cannot find -lmono-2.0`

### ISSUE THREAD

**Issue by jthomas** [frol/docker-alpine-mono#5]
I'd like to use `mkbundle` to bundle a static binary with the mono runtime built-in with the following command:

```
mcs hello.mono
mkbundle --deps --static hello.exe -o hello
```

I've installed `binutils` and `gcc` to set up the compile toolchain for `mkbundle`. Running the `mkbundle` command fails with the following message.

```
OS is: Linux
Sources: 1 Auto-dependencies: True
   embedding: /mnt/hello.exe
   embedding: /usr/lib/mono/4.5/mscorlib.dll
AS = as (default)
[execute cmd]: as -o temp.o temp.s
Compiling:
CC = cc (default)
[execute cmd]: cc -o 'hello' -Wall `pkg-config --cflags mono-2` temp.c  `pkg-config --libs-only-L mono-2` -Wl,-Bstatic -lmono-2.0 -Wl,-Bdynamic `pkg-config --libs-only-l mono-2 | sed -e "s/\-lmono-2.0 //"` temp.o
/usr/lib/gcc/x86_64-alpine-linux-musl/5.3.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lmono-2.0
collect2: error: ld returned 1 exit status
ERROR: [Fail] 256
```

Any ideas as to whether this will be possible?

**Comment by frol** [comment]
This image is based on a glibc-based mono package from Arch Linux (there was no musl libc support in mono when I bootstrapped this image, so I chose glibc hacking). Currently, there are mono packages in the edge/testing Alpine repository, so I suggest you just give it a try: 

```Dockerfile
FROM alpine

RUN apk add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing --no-cache mono mono-dev musl-dev binutils gcc
```

**Comment by jthomas** [comment]
Aha - it works! 

Thanks for the help.
